In [1]:
import numpy as np

In [8]:
np.array(range(1,7))
print(a.__repr__())
print(a)    #호출시 __Str__()호출
print(a.__str__())
a

array([[ 1, 20,  3],
       [ 4,  5,  6]])
[[ 1 20  3]
 [ 4  5  6]]
[[ 1 20  3]
 [ 4  5  6]]


array([[ 1, 20,  3],
       [ 4,  5,  6]])

In [3]:
a = np.array([1,2,3,4,5,6])
b = a.reshape(2,-1)
print('a',a)
print('b',b)
a[1]=20
b

a [1 2 3 4 5 6]
b [[1 2 3]
 [4 5 6]]


array([[ 1, 20,  3],
       [ 4,  5,  6]])

In [4]:
a = np.array([[1,2,3],[4,5,6]])
b = a.ravel()
print('a',a)
print('b',b)

a[0][1]=20
b

a [[1 2 3]
 [4 5 6]]
b [1 2 3 4 5 6]


array([ 1, 20,  3,  4,  5,  6])

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
b = a.flatten()
print('a',a)
print('b',b)

a[0][1]=20
b