<a href="https://colab.research.google.com/github/keulreobeu/bigdate_student/blob/main/%EC%83%88%EC%8B%B9_%ED%97%AC%EC%8A%A4%EC%BC%80%EC%96%B4_%EC%84%9C%EB%B9%84%EC%8A%A4%EA%B8%B0%ED%9A%8D/Python_%EB%8D%B0%EC%9D%B4%ED%84%B0%EA%B5%AC%EC%A1%B0_H.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python 기초 문법: 데이터구조

`작성자: 최원칠 강사`   
`traveler4d@gmail.com`


## 여러 값을 묶은 데이터구조
파이썬을 활용하여 데이터분석이나 프로그램을 만들기 위해서는 하나의 데이터가 아닌 여러개의 데이터가 많이 필요하게 됩니다. 이때 여러개의 데이터를 특정한 형태와 규칙에 맞게 관리하는 구조체를 데이터 구조라고 합니다.  

파이썬에서 데이터구조는 보통 하나의 객체로 정의가 되어있기 때문에 하나의 변수에 할당이 됩니다. 즉, 여러개의 데이터가 하나의 변수에 보관되여 효율적으로 관리가 될 수 있습니다.

**파이썬 대표 데이터구조**
- 리스트(list)
- 튜플(tuple), 문자열(str)
- 사전(dictionary)
- 배열(array)

### 가변 시퀀스 리스트

#### 리스트 구조와 특징
리스트는 여러 데이터를 순서대로 연결시킨 가변적인 시퀀스 데이터 구조로 파이썬에서 가장 대표적으로 사용되는 구조입니다.

<center><img src="https://drive.google.com/thumbnail?id=1_QF3A42XeMG1XcJ6APt113z9m_muudl_&sz=w1000" width="600"/></center>

그림처럼 데이터를 순서대로 연결하여 저장하며, 변수에 접근시 연결점 통해 여러 데이터를 순차적으로 관리할 수 있는 구조입니다.

- **연결 구조**
    - 여러 데이터를 순서대로 연결시킨 시퀀스 데이터 구조
    - 순서(index)를 가지고 있음
    - 데이터를 순서대로 따라가야 접근 가능하여, 접근 속도가 느림
    - 메모리 공간의 활용성이 좋음
- **가변 특성**
    - 여러 타입을 동시에 지니며 확장이 유연함
    - 자유롭게 데이터를 수정하고 추가 가능


#### 리스트 생성
파이썬에서 내부적으로 미리 구현된 기본 데이터구조는 특수 기호를 활용하여 리터럴 방식으로 생성이 가능합니다.

**리스트 생성 방법**
- 대괄호를 사용하여 빈 리스트를 표시하기: `[]`
- 대괄호를 사용하여 쉼표로 항목 구분하기: `[a], [a, b, c]`
- 리스트 컴프리헨션 사용하기: `[x for x in iterable]`
- 내장함수 생성자를 사용하기: `list()` 또는 `list(iterable)`

In [ ]:
# 비어있는 리스트 생성
empty = []
print(empty)

# 데이터를 넣어 리스트 생성
point = [5000, 6000, 7000, 6000, 9000]
print(point)


[]
[5000, 6000, 7000, 6000, 9000]


In [ ]:
# 다양한 타입이 들어올 수 있음
types = ['파이썬', 5000, '기초', 6.215, '사전학습', True]
print(types)

['파이썬', 5000, '기초', 6.215, '사전학습', True]


In [ ]:
# list() 함수 활용하여 생성 (형변환)
empty = list() # empty = []
print(empty)
seq = list(range(1, 20))
print(seq)

[]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]


In [ ]:
# for문과 if문을 활용한 리스트생성 (컴프리헨션)
seq_num = [x for x in range(1,10)]
print(seq_num)

seven_mul = [x for x in range(1,101) if x%7==0]
print(seven_mul)

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98]



#### 리스트의 메서드
리스트는 가변 특성을 가진 만큼 구조를 변형하는 다양한 요소의 메서드(함수)가 포함되어 있습니다.
- `append(x)`: x를 맨뒤에 추가  
- `extend(x)` : x를 이어 붙이기(구조내 요소를 추가)  
- `sort()` : 내부 요소를 정렬  
- `reverse()` : 내부 요소를 반대로 구성   
- `pop()` : 마지막 순서 항목을 반환후 리스트에서 제거   
- `clear()` : 모든 항목을 제거   
- `count(x)` : x 가 리스트에 나타나는 횟수를 반환
- `insert(i,x)` : i순서에 x를 삽입    


In [ ]:
# append : 리스트 맨뒤에 항목 추가하기
point = [5000, 6000, 7000, 6000, 9000]
point.append(10000)
point

[5000, 6000, 7000, 6000, 9000, 10000]

In [ ]:
# append는 내부 항목을 그대로 추가
point = [5000, 6000, 7000, 6000, 9000]
point.append([6000, 5000])
print(point)

# extend : 또다른 리스트를 이어 붙이기(구조내 요소를 추가)
point = [5000, 6000, 7000, 6000, 9000]
point.extend([6000, 5000])
print(point)

# + 연산을 활용하여 이어 붙이기 가능
concat = [5000, 6000, 7000, 6000, 9000] + [6000, 5000]
print(concat)

[5001, 6001, 7001, 6001, 9001]
[5000, 6000, 7000, 6000, 9000, 6000, 5000]
[5000, 6000, 7000, 6000, 9000, 6000, 5000]


In [ ]:
# sort : 내부 요소를 정렬
point = [9000, 5000, 6000, 7000, 6000]
point.sort()
print(point)

# reverse : 내부 요소를 반대로 구성
point = [9000, 5000, 6000, 7000, 6000]
point.reverse()
print(point)

[5000, 6000, 6000, 7000, 9000]
['6000', 7000, 6000, 5000, 9000]


### 시퀀스 연산
파이썬은 데이터구조를 다루기 위해 기본 데이터구조에 통용 적으로 사용될 수 있는 다양한 명령어 기법을 제공합니다.  

데이터구조를 가진 인스턴스에서 메소드를 통해 독립적으로 사용되는 것이 아닌 통용적인 명령어를 사용하여 활용한다는 것에 주의해야 합니다.


#### 인덱싱
인덱싱은 데이터구조에서 특정 데이터를 찾아가기 위해 제공되는 시퀀스 연산입니다.

- `데이터구조[인덱스]` : 데이터구조내 특정 인덱스(기준)에 해당하는 데이터에 접근    
- 인덱스는 데이터구조에 따라 다양한 형태로 존재

<center><img src="https://drive.google.com/thumbnail?id=1h5ziL6xgvdYrWraRZEm9sEKHzjtgByoC&sz=w1000" width="500"/></center>

In [ ]:
# [index]를 활용한 데이터 선택
point = [5000, 6000, 7000, 6000, 9000]

print(point[0])
print(point[2])
# 음수를 활용하여 역순으로 인덱싱 가능
print(point[-1])

5000
7000
9000


> index는 항상 0부터 시작함을 주의

#### 슬라이싱
슬라이싱의 인덱싱의 확장으로 인덱싱을 `:`기호를 통해 특정 범위로 확장하여 데이터구조의 부분을 가져옵니다.

- `데이터구조[시작인덱스:끝인덱스]` : `시작인덱스` 부터 `끝인덱스-1` 까지에 해당하는 데이터들을 부분으로 가져옴

In [ ]:
# [start:end]을 활용해 범위 지정 가능(슬라이싱), 끝 인덱스 미포함
point = [5000, 6000, 7000, 6000, 9000]
print(point[2:4])
# 앞에 0은 생략 가능
print(point[:3])

[7000, 6000]
[5000, 6000, 7000]


> 슬라이싱에서 끝인덱스의 -1 만큼만 접근함을 주의

In [ ]:
# 음수 인덱스로 뒤에순서를 지정 가능
point = [5000, 6000, 7000, 6000, 9000]
# 마지막 인덱스는 생략
print(point[-2:])

[6000, 9000]


#### 인덱싱으로 데이터 수정
가변특성을 가진 데이터구조는 인덱싱 또는 슬라이싱을 통해 해당 인덱스의 데이터를 수정할 수 있습니다.

이때 `del` 연산을 추가로 활용하면 특정 인덱스의 데이터를 삭제 가능합니다.

In [ ]:
# 인덱스를 활용한 업데이트
point[3] = 60000
point

[5000, 6000, 7000, 60000, 9000]

In [ ]:
# 인덱스가 없으면 에러
point[6] = 60000

IndexError: list assignment index out of range

In [ ]:
# 인덱스에 접근하여 삭제
del point[3]
point

[5000, 6000, 7000, 9000]

#### len(),max(),min(),zip()
`len()` 함수에 데이터구조를 입력하면 데이터구조의 총 길이(데이터개수) 가 반환됩니다. 유사하게 데이터구조의 정보를 반환해주는 함수들이 여러 존재합니다.

- `len(데이터구조)`: 데이터구조의 길이를 반환
- `max(데이터구조)`: 데이터구조내 최대 값을 반환
- `min(데이터구조)`: 데이터구조내 최소 값을 반환
- `zip(데이터구조,데이터구조)`: 두 데이터구조를 동일 인덱스끼리 묶어 반환

In [ ]:
point = [5000, 6000, 7000, 6000, 9000]

print(f'길이: {len(point)}')
print(f'최대: {max(point)}')
print(f'최소: {min(point)}')
# zip 객체 생성후 다시 리스트 변환
z = zip(point,[1,2,3,4,5])
print(f'정렬: {list(z)}')

길이: 5
최대: 9000
최소: 5000
정렬: [(5000, 1), (6000, 2), (7000, 3), (6000, 4), (9000, 5)]


#### range() 활용 반복 인덱싱

`range()` 함수와 `len()` 함수를 활용하여 `for`문에서 데이터구조에 반복작업을 인덱싱을 통해 진행할 수 있습니다.

In [ ]:
for i in range(len(point)):
    print(point[i])

#### enumerate() 활용
`enumerate()` 함수를 통해 다양한 상황에서의 반복 인덱싱 작업을 보다 쉽게 구현할 수 있습니다.

- `enumerate(데이터구조)`: 데이터구조의 데이터를 순서대로 반환할때 `(순서, 데이터)`로 묶어서 반환

In [ ]:
point = [5000, 6000, 7000, 6000, 9000]

for i, v in enumerate(point):
    print(f'순서:{i}, 데이터:{v}')
    point[i] = v + 1000

print(point)


#### in 비교연산
**if** 문에서 **in** 비교연산을 데이터구조와 함께 사용하면 데이터의 포함 여부를 알 수 있습니다.

- `if 데이터 in 데이터구조` : `데이터구조에` `데이터`가 포함되어 있으면 `True`

In [ ]:
# if 데이터 in 데이터구조

if 0 in [1,2,3,4]:
    print('zero in')

if 1 in [1,2,3,4]:
    print('one in')

### 실습3


#### [실습1]
관심있는 메뉴 3개를 묶은 menu 리스트를 생성하고 append( )로 메뉴 하나 더 추가하세요


In [ ]:
list = ['감자', '양파', '마늘']
list.append('삼겹살')
print(list)

['감자', '양파', '마늘', '삼겹살']


#### [실습2]
menu에서 세번째 메뉴를 '우동'으로 변경하고 세번째~마지막 메뉴를 선택하여 출력하세요

In [ ]:
list[2] = '우동'
print(list[2:])

['우동', '삼겹살']


#### [실습3]
menu에서 반복문을 활용해 리스트에 있는 메뉴를 순서대로 출력하세요


In [ ]:
for i in range(len(list)):
    print(list[i])

감자
양파
우동
삼겹살


#### [실습4]
다음 리스트 내부에 값을 1씩 더한 값으로 수정하여 리스트를 출력하세요

In [ ]:
nums = [1,2,3,4,5]
for i in range(len(nums)):
    nums[i] = nums[i] + 1
print(nums)

[2, 3, 4, 5, 6]


#### [실습5]
다음 리스트 내부에 항목에서 '*' 를 뺀 항목만 가지는 리스트를 생성하고 출력하세요
 - 반복문과 append 활용

In [ ]:
nums = [1,2,3,'*',5,6,7,'*',9,10]
list = []


for i in range(len(nums)):
    if nums[i] != '*':
        list.append(nums[i])
print(list)


[1, 2, 3, 5, 6, 7, 9, 10]




#### [실습6]
다음 세 리스트를 이어붙이고 이름 순으로 정렬하여 출력하세요


In [ ]:
list1 = ['a','f','c']
list2 = ['b','e']
list3 = ['a','f']


In [ ]:
list = list1 + list2 + list3
list.sort()
print(list)

['a', 'a', 'b', 'c', 'e', 'f', 'f']


#### [심화1]
다음 리스트(names) 안에 입력된 이름으로 생성된 Customer 인스턴스를 보관하는 리스트를 만들고 출력하세요. 고객 번호는 이름 순서대로 1씩 증가하는 값으로 설정합니다.

    names = ['김입금','나은행','최대출','신한나','국민협']

    class Customer:

        def __init__(self, name, c_id):
            self.name = name
            self.c_id = c_id
            self.amount = 0

        def add_amount(self, amount):
            self.amount += amount
            # self.amount = self.amount + amount

        def sub_amount(self, amount):
            self.amount -= amount

        def get_amount(self):
            return self.amount

In [ ]:
class Customer:

    def __init__(self, name, c_id):
        self.name = name
        self.c_id = c_id
        self.amount = 0

    def add_amount(self, amount):
        self.amount += amount
        # self.amount = self.amount + amount

    def sub_amount(self, amount):
        self.amount -= amount

    def get_amount(self):
        return self.amount

In [ ]:
names = ['김입금','나은행','최대출','신한나','국민협']
list = []
for i in range(0,len(names)):
    cst = Customer(names[i],i+1)
    list.append(cst)

#### [심화2]
[심화1]에서 만든 리스트의 2번 고객에 1000원을 추가하고 4번 고객에는 4000원을 추가한뒤 고객이 각각 가지고 있는 금액을 전부 출력하세요

    -출력예시-
    김입금 0
    나은행 0
    최대출 1000
    신한나 0
    국민협 4000

In [ ]:
list[2].add_amount(1000)
list[4].add_amount(4000)
for i in range(0,len(list)):
    print(list[i].name,list[i].amount)

김입금 0
나은행 0
최대출 1000
신한나 0
국민협 4000


### 불변 시퀀스 튜플(tuple)과 문자열(str)
튜블과 문자열은 리스트와 동일하게 시퀀스 특성을 가지지만, 내부적으로 구조를 바꿀수 없는 **불변 시퀀스형** 데이터구조 입니다.  

#### 튜플 특징
튜플은 리스트보다 가볍게 활용되는 구조로, 단순히 여러 데이터를 순서대로 저장하여 전달하기 위한 목적으로 사용됩니다.

- 여러 데이터를 묶음으로 보관하는 불변 시퀀스 데이터 구조
- 리스트처럼 순서대로 여러 데이터를 보유
- 리스트와 반대로 데이터 추가 및 수정 불가능
- 리스트에 비해 가볍고 빠른 접근 속도를 가짐


#### 튜플 생성 및 표현
- `()`기호를 활용해서 튜플 생성
- `()`기호는 생략 가능

In [ ]:
aa = (1, 2, 3)
bb = '아침', '점심', '저녁'

print(type(aa))
print(type(bb))

<class 'tuple'>
<class 'tuple'>


In [ ]:
# 인덱싱 및 슬라이싱 가능
print(aa[0])
print(bb[1:])

1
('점심', '저녁')


In [ ]:
# 추가/업데이트 불가능, 내부 변환 메소드도 없음
aa[0] = 4

TypeError: 'tuple' object does not support item assignment

In [ ]:
# 튜플 요소의 순서를 맞추어 변수 할당 가능

a, b = ('아침', '점심')
print(a)
print(b)

아침
점심


#### 문자열 특징
문자열을 기본 데이터타입으로 사용되면서도 내부적으로는 **문자(유니코드)**의 **배열**로 구성된 데이터구조입니다.

- 유니코드 코드 포인트의 불변 시퀀스 데이터구조
- 문자열을 제어하는 다양한 메소드 포함 (내부 구조 변형X)
- 리스트와 동일하게 순서로 인덱싱
- 인덱싱을 활용한 데이터 수정 불가



#### 문자열 데이터구조 활용

문자열은 튜플과 같은 불변 특성이지만 튜플과는 다르게 문자열을 제어하는 다양한 메소드가 있습니다. 이때 메소드는 기존 문자열 구조는 변형시키지 않고 변형된 새로운 문자열을 반환합니다.


- `replace(x,y)` : x문자열을 y문자열로 대체  
- `strip()` : 앞뒤 공백 제거
- `split(x)` : x문자열을 기준으로 분리하여 리스트생성
- `encode()` : 문자열의 인코딩 버전 변환 기본은 utf-8
- `find(substr)` : 문자열내에 포함되는 서브 문자열 첫 인덱스 반환환

In [ ]:
# 인덱싱과 슬라이싱 가능
s = '파이썬 기초 데이터구조'
print(s[2])
print(s[4:8])

썬
기초 데


> 불변 시퀀스 구조이므로 인덱싱으로 통한 수정은 불가능

In [ ]:
# replace() : 원하는 부분문자열을 다른 문자열로 대체
s = '파이썬 기초 데이터구조'
s1 = s.replace('기초', '심화')
s1

'파이썬 심화 데이터구조'

> 항상 변수를 통해 변환된 새로운 문자열을 할당해주어야 활용 가능

In [ ]:
# strip() : 앞뒤 공백 제거
s = '   파이썬 기초 데이터구조\n'
s = s.strip()
s

파이썬 기초 데이터구조


In [ ]:
# split() : 원하는 문자열을 기준으로 분리하여 리스트생성
s = '파이썬 기초 데이터구조'
s1 = s.split(' ') # 공백(띄어쓰기) 기준으로 분리
s1


['파이썬', '기초', '데이터구조']

### 해시셋과 딕셔너리
헤시셋(집합)과 딕셔너리는 앞서 배운 순서를 기반으로 데이터를 보관하지 않고 해쉬 키를 기반으로 데이터를 보관하는 데이터구조입니다.

#### 해시셋(집합) 특징
해시셋은 메모리에 해시 테이블을 만들어 데이터를 해당 테이블에 보관하고 관리합니다. 데이터를 테이블에 저장할 때는 해시 연산을 이용하며 해시연산 결과에 따라 테이블의 특정 위치가 할당됩니다.

<center><img src="https://drive.google.com/thumbnail?id=1Kltb9m6RG2GMND7AsfftCMNEeIj7xb_X&sz=w1000" width="500"/></center>
**해시 테이블**
- 저장하려는 데이터를 해시 연산하여 테이블내 저장될 위치를 찾음
- 동일 데이터는 같은 위치에 참조되기 때문에 중복 항목이 없음
- 배열, 리스트와 다르게 저장 순서를 기억하지 않음
- 해시를 통해 바로 데이터 위치를 파악 가능하여 읽기,쓰기속도가 빠름
- 해시 연산이 가능한 객체만 저장 가능
- 실제 테이블에는 데이터의 참조 포인터가 저장

#### 해쉬셋 생성 과 표현
해쉬셋은 `{}`에 항목을 입력하여 생성 가능하며, `add()` 함수를 이용해 데이터추가가 가능합니다.

In [ ]:
# 순서가 없는 해쉬셋
s = {'돈까스','치킨','덮밥'}
s.add('우동')
s

{'덮밥', '돈까스', '우동', '치킨'}

In [ ]:
set(('돈까스','치킨','덮밥','덮밥'))

{'덮밥', '돈까스', '치킨'}

In [ ]:
# 중복이 되지 않는 해쉬셋
s = {'돈까스','치킨','덮밥','치킨'}
s.add('덮밥')
s

{'덮밥', '돈까스', '치킨'}

#### 딕셔너리 특징
딕셔너리는 **키(key)** 와 **값(value)** 매핑하여 키를 기준으로 데이터를 보관하는 데이터구조로, 집합과 동일하게 **키(key)**를 해시 연산과 테이블을 이용하여 보관하고 여기에 **값(value)**을 연결시킵니다.

<center><img src="https://drive.google.com/thumbnail?id=10pN22FTgmcgNu03kdGb1XUvZaq0RreTD&sz=w1000" width="600"/></center>

- 해시 가능 객체를 특정 객체와 매핑하여 *키(key)* 와 *값(value)* 매핑구조를 가짐
- 해시 가능 하지 않은 객체들(리스트, 딕셔너리)등은 *key*로 사용불가
- *값(value)* 은 어떤 타입의 데이터도 사용가능
- *key*는 해쉬특성을 가져 찾는 속도와 저장속도가 빠름
- 웹통신 데이터구조인 json형과 비슷한 구조로 많이 활용


#### 딕셔너리 생성과 사용
딕셔너리도 해시셋과 동일하게 `{}` 기호를 이용하지만, 내부적으로 `:` 기호를 활용하여 키와 값을 매핑하여 생성합니다.

- `{}` 안에 쉼표로 구분된 `key:value` 쌍을 나열하기: `{key1:value1 , key2:value2}`   
- 딕셔너리 컴프리헨션 사용하기: `{x: x ** 2 for x in range(10)}`   
- 함수 사용하기: `dict()`

In [ ]:
# 키:값 매핑으로 딕셔너리 생성
product1 = {'제품명':'팜봇', '가격':500000, '카테고리':'Aiot'}
product1

{'제품명': '팜봇', '가격': 500000, '카테고리': 'Aiot'}

In [ ]:
# 키를 입력하여 인덱싱
product1['제품명']

'팜봇'

In [ ]:
# 없는키는 에러
product1['할인율']

KeyError: '할인율'

In [ ]:
# 메서드 get()을 활용하면 에러 방지
product1.get('할인율',0)

0

In [ ]:
# 시퀀스 연산자에 새로운 키를 넣고 할당하여 키:값 추가
product1['재고'] = 10
product1

{'제품명': '팜봇', '가격': 500000, '카테고리': 'Aiot', '재고': 10}

In [ ]:
# 시퀀스 연산자에 기존 키를 넣고 할당하여 값 변경
product1['재고'] = 5
product1


{'제품명': '팜봇', '가격': 500000, '카테고리': 'Aiot', '재고': 5}

In [ ]:
# del 연산을 활용한 키:값 제거
del product1['카테고리']
product1

{'제품명': '팜봇', '가격': 500000, '재고': 5}

In [ ]:
# 키 목록 반환
product1.keys()

dict_keys(['제품명', '가격', '재고'])

In [ ]:
# 리스트로 키 목록 반환
list(product1)

['제품명', '가격', '재고']

In [ ]:
# 값 목록 반환
product1.values()

dict_values(['팜봇', 500000, 5])

In [ ]:
# 반복문에는 키가 이터러블
for p in product1:
    print(p)

제품명
가격
재고


#### 딕셔너리의 계층 구조
딕셔너리의 *값(value)* 에는 또 다른 데이터 구조(리스트, 딕셔너리 등)를 할당할 수 있어, **계층적 구조**를 가질 수 있습니다.

이런 계층 구조는 다양한 데이터를 하나의 묶음으로 보관할 수 있어 주로 **빅데이터**를 보관 하고 전달하는 구조로 활용되며, 대규모 데이터 통신 구조인 **JSON**과 쉽게 변환이 가능합니다.

In [ ]:
# 계층 구조로 구성
product1['카테고리'] = ['AI','Aiot','Iot','data']
product1

{'제품명': '팜봇', '가격': 500000, '재고': 5, '카테고리': ['AI', 'Aiot', 'Iot', 'farm']}

In [ ]:
# 계층적 구조를 가지는 딕셔너리
d = {
    'id': 1,
    'name': '원칠',
    'company': {
        'name': 'taveler4d',
        'site': 'aaa.www.ggg',
        'phone': '02-2222-2222',
        'city': '구로디지털단지'},
    'project': [
        {'name': 'pandas', 'pid': '0014'},
        {'name': 'aiot', 'pid': '0023'}
    ],
    'phone': '010-1111-2222'
}

# 계층 구조에서 중첩 키 인덱싱
print(d['company']['city'])
print(len(d['project']))
print(d['project'][0]['name'])

구로디지털단지
2
pandas


### 실습4

#### [실습1]
'메뉴이름' 키에는 메뉴이름이, '가격' 키에는 해당 메뉴의 가격이 입력된 딕셔너리 하나를 생성하세요


In [ ]:
dict = {'메뉴이름':'치킨', '가격':10000}

print(dict)

{'메뉴이름': '치킨', '가격': 10000}


#### [실습2]
다음 두개의 리스트를 활용하여 실습1 에서 구성한 형태의 딕셔너리를 3개 만들고 이를 보관하는 리스트를 만들어 출력하세요

    menu = ['치킨','피자','국밥']
    price = [20000, 23000, 10000]

    - 출력 결과 -
    [{'메뉴이름': '치킨', '가격': '치킨'},
     {'메뉴이름': '피자', '가격': '피자'},
     {'메뉴이름': '국밥', '가격': '국밥'}]

In [ ]:
menu = ['치킨','피자','국밥']
price = [20000, 23000, 10000]

dict_list = []

for i in range(0, len(menu)):
    dict = {'메뉴이름': menu[i], '가격': price[i]}
    dict_list.append(dict)

print(dict_list)

[{'메뉴이름': '치킨', '가격': 20000}, {'메뉴이름': '피자', '가격': 23000}, {'메뉴이름': '국밥', '가격': 10000}]


#### [실습3]
실습2에서 만든 리스트에서 1번 메뉴의 가격을 인덱싱하여 출력하세요

In [ ]:
dict_list[0]['가격']

20000

#### [실습4]
다음 s1 문자열을 띄어쓰기 단위로 잘라 목록으로 만들고, stop_words에 해당하는 단어를 제외한 단어만 담긴 리스트를 만들어 출력하세요

    s1 = '새싹 빅데이터 데이터분석 데이터구조 파이썬 시각화 판다스'
    stop_words = '데이터구조'
    
    - 출력 결과 -
    ['새싹', '빅데이터', '데이터분석', '파이썬', '시각화', '판다스']

In [ ]:
s1 = '새싹 빅데이터 데이터분석 데이터구조 파이썬 시각화 판다스'
stop_words = '데이터구조'

In [ ]:
list = s1.split(' ')
list.remove(stop_words)
print(list)

['새싹', '빅데이터', '데이터분석', '파이썬', '시각화', '판다스']


#### [실습5]
3개의 데이터구조에서 orders의 3번째 딕셔너리에 해당하는 고객의 이름과 첫번째 제품의 이름을 출력하세요. 이때 변수와 인덱싱만을 활용해야 합니다.

    - 출력결과 -
    파이썬, 자전거
    


In [ ]:
users = {'123':'G밸리',
         '124':'파이썬',
         '125':'데이터분석',}

products = {'a':['노트북', 200],
            'b':['자전거', 15],
            'c':['샴푸', 2],
            'd':['셔츠', 1],
            'e':['초코렛', 1]}

orders = [{'user_id':'123', 'products':['a','c']},
         {'user_id':'125', 'products':['e']},
         {'user_id':'124', 'products':['b','d','e']}]


users.get(orders[2]['user_id']), products.get(orders[2]['products'][0])[0]

('파이썬', '자전거')

#### [심화1]
[실습5]의 3개 딕셔너리를 for문과 인덱싱을 활용하여 다음과 같은 리스트-딕셔너리 구조로 만들어 출력하세요

    -출력결과-
    [{'주문자': 'G밸리', '상품명': '노트북', '가격': 200}, {'주문자': 'G밸리', '상품명': '샴푸', '가격': 2}, {'주문자': '데이터분석', '상품명': '초코렛', '가격': 1}, {'주문자': '파이썬', '상품명': '자전거', '가격': 15}, {'주문자': '파이썬', '상품명': '셔츠', '가격': 1}, {'주문자': '파이썬', '상품명': '초코렛', '가격': 1}]


In [ ]:
users = {'123':'G밸리',
         '124':'파이썬',
         '125':'데이터분석',}

products = {'a':['노트북', 200],
            'b':['자전거', 15],
            'c':['샴푸', 2],
            'd':['셔츠', 1],
            'e':['초코렛', 1]}

orders = [{'user_id':'123', 'products':['a','c']},
         {'user_id':'125', 'products':['e']},
         {'user_id':'124', 'products':['b','d','e']}]


In [ ]:
list  = []

for i in range(0,len(orders)):
    id, pd = orders[i].values()
    for j in range(0,len(pd)):
        list.append({'주문자':users[id],'상품명': products[pd[j]][0], '가격' : products[pd[j]][1]})

list

[{'주문자': 'G밸리', '상품명': '노트북', '가격': 200},
 {'주문자': 'G밸리', '상품명': '샴푸', '가격': 2},
 {'주문자': '데이터분석', '상품명': '초코렛', '가격': 1},
 {'주문자': '파이썬', '상품명': '자전거', '가격': 15},
 {'주문자': '파이썬', '상품명': '셔츠', '가격': 1},
 {'주문자': '파이썬', '상품명': '초코렛', '가격': 1}]


## 배열
배열은 컴퓨터 자료구조의 가장 기초적인 구조로 단순히 저장하고자 하는 데이터들을 한공간에 순서적으로 나열한 데이터구조입니다.

하지만 파이썬은 다른 언어와 다르게 기초 구조로 리스트를 활용하므로, 배열을 활용하기 위해 외부 라이브러리인 **numpy** 모듈을 설치해주어야 합니다.


#### 배열 특징
배열은 리스트와 표면적인 표현 방식은 유사하지만 내부 구조적으로 많은 차이가 존재합니다.

<center><img src="https://drive.google.com/thumbnail?id=1av9Ok3P5QJGdIOxjZCdM3iNFY_6pYObn&sz=w1000" width="500"/></center>

- **고정 구조**
    - 저장될 데이터들의 크기와 개수를 통해 정확한 공간을 계산하여 할당
    - 하나의 배열에는 동일한 타입의 데이터만 저장 가능
    - 항목의 타입과 크기가 정해져야 생성 가능
    - 공간의 활용 효율성이 리스트에 비해 떨어짐
- **데이터 접근 방식**
    - 항목의 순서를 통해 항목 접근 가능
    - 명확한 공간 배치로 인해 특정 순서의 데이터를 바로 찾아갈 수 있음
    - 접근 속도가 빠르고 연산 효율이 좋음


### numpy를 활용한 배열
**numpy**는 **ndarray**라는 형식을 활용해서 다차원의 배열형식을 만들고 다양한 연산과 처리를 지원합니다.

#### numpy 설치

외부라이브러리는 **pip 명령어**를 활용해 설치가 가능합니다. 이때 `pip`는 시스템 명령어 이므로 주피터 환경에서는 `!`를 붙여주어야 합니다.

- `!pip install 라이브러리이름` : 해당 라이브러리를 설치

In [ ]:
# numpy 설치
!pip install numpy

In [ ]:
# 넘파이 모듈임포트
import numpy as np

#### 배열생성
배열을 만들기 위해서는 기본적으로 데이터의 타입과 데이터의 개수가 결정되어야 합니다.
따라서 미리 구현된 데이터구조를 배열로 변환하는 방식이나 특정 형식과 크기로 초기화된 배열을 만드는 방식으로 배열을 생성합니다.

- 구현된 이터러블을 활용해 asarray()로 생성: `np.asarray(iterable)`    
- 지정 모형의 0으로 초기화 시키기: `np.zeros((3,2))`    
- 지정 모형의 1으로 초기화 시키기: `np.ones((3,2))`    
- 지정 모형의 0~1 랜덤 초기화 시키기: `np.random.rand(3,2)`    

In [ ]:
# array() 함수로 배열 생성
x = [1, 2, 4, 8]
y = np.array(x)
print(y)
# shape 변수로 형상 확인
print(y.shape)

[1 2 4 8]
(4,)


#### 다차원 배열 형상 이해
배열은 정형적인 일정한 모형으로 중첩된 구조인 **다차원 구조** 특징을 가집니다.

<center><img src="https://drive.google.com/thumbnail?id=17Djg-VXMcwMuWdGc7wFxh405vW0L2rkj&sz=w1000" width="600"/></center>

- **축 (Axis):** 배열의 각 차원에서 데이터가 확장되는 방향
- **차원 (Dimension)**: 배열에서 데이터가 구성된 축(axis)의 수
- **형상(shape):** 배열의 각 축(axis)에 해당하는 데이터 개수를 표현

In [ ]:
# 다차원 배열
array1d = np.array([1,2,3,4,5])

array2d = np.array([[1,2,3,4,5],
                    [6,7,8,9,0]])

array3d = np.array([[[1,2,3,4,5],
                     [6,7,8,9,0]],
                    [[2,3,4,5,6],
                     [7,8,9,0,1]],
                    [[3,4,5,6,7],
                     [8,9,0,1,2]]])

print(array1d.shape)
print(array2d.shape)
print(array3d.shape)

(5,)
(2, 5)
(3, 2, 5)


#### 다차원 배열 인덱싱
다차원 배열에서는 `[]` 내부에 `,` 기호를 이용하여 **축(axis)** 단위로 인덱싱이 가능합니다.

In [ ]:
# 차원 축에 맞게 인덱싱

print(array1d[0])
print(array2d[0,2])
print(array3d[0,1,3])

1
4
9


In [ ]:
# 다차원 배열 슬라이싱
print('1번축 슬라이싱:')
print(array2d[0,1:4])

print('0,1번축 슬라이싱:')
print(array2d[:,1:4])

print('중간축만 슬라이싱:')
print(array3d[0,:,1])

print('여러축 슬라이싱 요약:')
print(array3d[...,0])

1번축 슬라이싱:
[3 4 5]
0,1번축 슬라이싱:
[[3 4 5]
 [7 8 9]]
중간축만 슬라이싱:
[2 7]
여러축 슬라이싱 요약:
[[1 6]
 [2 7]
 [3 8]]


In [ ]:
# 인덱싱을 통한 데이터 할당
array2d[0,1] = 10
array2d

array([[ 1, 10,  3,  4,  5],
       [ 6,  7,  8,  9,  0]])

In [ ]:
# 동일한 차원의 데이터를 할당해야함
array2d[0] = [2,3,4,5,6]
array2d

array([[2, 3, 4, 5, 6],
       [6, 7, 8, 9, 0]])

### 다차원 배열 연산
numpy는 다차원 배열의 효율적인 연산 방식을 제공합니다.

#### 배열에서 연산 활용
배열에서 **연산자** 활용시 같은 인덱스에 해당하는 데이터간 일괄연산이 진행되며, 특수 연산에 대한 다양한 **연산 함수**를 활용할 수 도 있습니다.

In [ ]:
# 일괄 산술 연산
array2d * 2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18,  0]])

In [ ]:
# 다양한 연산 함수 제공
print(np.sqrt(y)) # 제곱근
print(np.power(y, 2)) # 거듭제곱
print(np.log(y)) # 자연로그
print(np.exp(y)) # 지수

[1.         1.41421356 2.         2.82842712]
[ 1  4 16 64]
[0.         0.69314718 1.38629436 2.07944154]
[2.71828183e+00 7.38905610e+00 5.45981500e+01 2.98095799e+03]


#### 원하는 축을 선택하여 연산
배열 연산 함수에서 `axis` 인자 활용하면 축 단위로 연산이 가능합니다.

In [ ]:
array2d

array([[2, 3, 4, 5, 6],
       [6, 7, 8, 9, 0]])

In [ ]:
# sum 함수를 활용하여 배열내 데이터 더하기 연산
np.sum(array2d)

50

In [ ]:
# axis 인자에 0을 할당하여 0번 축으로 더하기
np.sum(array2d, axis = 0)

array([ 8, 10, 12, 14,  6])

In [ ]:
# 1번 축으로 더하기
np.sum(array2d, axis = 1)

array([20, 30])

### 배열의 형상 변환
numpy는 배열의 형상을 바꿔주는 다양한 함수도 제공해 줍니다. 이때 형상 변환 시 절대적인 배열의 크기는 변할 수 없습니다.

In [ ]:
# reshape(배열, 형상) 배열을 입력한 형상으로 재구성
np.reshape(array3d,(30,))

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 3, 4,
       5, 6, 7, 8, 9, 0, 1, 2])

In [ ]:
# reshape는 순서대로 재구성
np.reshape(array3d,(5,6))

array([[1, 2, 3, 4, 5, 6],
       [7, 8, 9, 0, 2, 3],
       [4, 5, 6, 7, 8, 9],
       [0, 1, 3, 4, 5, 6],
       [7, 8, 9, 0, 1, 2]])

In [ ]:
# 전체 크기가 변하지 않는선에서 변환 가능
np.reshape(array3d,(5,2,3))

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [0, 2, 3]],

       [[4, 5, 6],
        [7, 8, 9]],

       [[0, 1, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [0, 1, 2]]])

In [ ]:
# -1을 활용하여 남은 형상 구현
np.reshape(array3d,(5,-1))

array([[1, 2, 3, 4, 5, 6],
       [7, 8, 9, 0, 2, 3],
       [4, 5, 6, 7, 8, 9],
       [0, 1, 3, 4, 5, 6],
       [7, 8, 9, 0, 1, 2]])

In [ ]:
# 형상에 1을 입력하여 비어있는 차원을 추가할 수 있음
np.reshape(array1d,(1,5))

array([[1, 2, 3, 4, 5]])

In [ ]:
# expand_dims 함수를 활용하여 원하는 축에 비어있는 차원을 추가
ed = np.expand_dims(array1d, axis = 0)
print(ed)
print(ed.shape)

[[1 2 3 4 5]]
(1, 5)


### 실습5
다음 작성된 2차원 배열 arr2d에 대하여 다음 문제를 해결하세요

In [ ]:
import numpy as np

arr2d = np.array([[1,2,3,4,5],
                [5,6,7,8,9],
                [9,1,2,3,4],
                [5,6,7,8,9],
               ])


#### [실습1]
다음 배열(arr2d)의 형상을 출력하세요

In [ ]:
arr2d

array([[1, 2, 3, 4, 5],
       [5, 6, 7, 8, 9],
       [9, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

#### [실습2]
다음 배열(arr2d)의 0번축의 1번, 1번축의 2번에 해당하는 데이터를 출력하세요


In [ ]:
arr2d[0,1], arr2d[1,2]

(np.int64(2), np.int64(7))

#### [실습3]
다음 배열(arr2d)의 0번축의 0 ~ 2번, 1번축의 2 ~ 4번에 해당하는 데이터를 출력하세요



In [ ]:
arr2d[0,:3], arr2d[1,2:5]

(array([1, 2, 3]), array([7, 8, 9]))

#### [실습4]
배열(arr2d)에 1번축 값들의 합으로 표현된 배열을 만들고 출력하세요


In [ ]:
arr2d[1].sum()

np.int64(35)

#### [실습5]
배열(arr2d)의 형상을 (2,2,5)로 변환하여 arr3d 변수에 할당하고 형상을 출력하세요


In [ ]:
arr3d = np.reshape(arr2d,(2,2,5))
arr3d

array([[[1, 2, 3, 4, 5],
        [5, 6, 7, 8, 9]],

       [[9, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]])

#### [실습6]
중첩 반복 문을 활용하여 arr2d 배열의 데이터에 하나씩 접근하여 출력하세요


In [ ]:
for i in range(0,len(arr2d)):
    for j in range(0,len(arr2d[i])):
        print(arr2d[i][j])

1
2
3
4
5
5
6
7
8
9
9
1
2
3
4
5
6
7
8
9
